[variables]
NIXPACKS_NO_CACHE = "1"

[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install] 
dependsOn = ['setup']
cmds = ['npm ci']

[phases.build]
dependsOn = ['install']
cmds = ['npm run build']

[start]
cmd = 'npm start' 